# Generated by Django 6.0.1 on 2026-02-10 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmedia',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.group'),
        ),
        migrations.AlterField(
            model_name='groupmedia',
            name='image',
            field=models.ImageField(upload_to='media/group-media/'),
        ),
    ]
