# Generated by Django 6.0.1 on 2026-02-11 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_groupmedia_group_alter_groupmedia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.country'),
            preserve_default=False,
        ),
    ]
