# Generated by Django 6.0.1 on 2026-02-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_groupdetail_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetail',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='main.group'),
        ),
    ]
