# Generated by Django 6.0.1 on 2026-02-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_groupdetail_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('completed', 'Tasdiqlandi'), ('rejected', 'Rad_etildi')], default='new', max_length=150),
        ),
        migrations.AlterField(
            model_name='memberdetail',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetail',
            name='affiliation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
