# Generated by Django 6.0.1 on 2026-02-05 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_member_status_alter_memberdetail_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='google_scholar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='orcid',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='scopus',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.university'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
