# Generated by Django 6.0.1 on 2026-02-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_fullname_contact_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
