# Generated by Django 6.0.1 on 2026-02-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesseminarsdetail',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
