# Generated by Django 6.0.1 on 2026-02-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_conferencesseminarsdetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstranslate',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
