# Generated by Django 6.0.1 on 2026-02-14 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_projectstranslate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preoject', to='main.group'),
        ),
    ]
