# Generated by Django 6.0.1 on 2026-02-16 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_projects_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.country'),
        ),
    ]
