# Generated by Django 6.0.1 on 2026-02-17 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_member_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, related_name='preoject', to='main.group'),
        ),
    ]
