# Generated by Django 6.0.1 on 2026-02-17 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_projects_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preoject', to='main.group'),
        ),
    ]
