# Generated by Django 6.0.1 on 2026-02-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_projects_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='main.group'),
            preserve_default=False,
        ),
    ]
